### ISSUE TITLE
unsupport language

### ISSUE THREAD

**Issue by liaostr** [yaaliuzhipeng/react-native-mlkit-translate-text#4]
unsupport language

<img width="310" alt="image" src="https://user-images.githubusercontent.com/13637497/210723881-c6f7ea8b-6b6e-4682-a0ac-aa76d963a631.png">

**Comment by noumantahir** [comment]
hit with same roadblock even with most basic of code snippet...

```
      if(await MLKitTranslator.isModelDownloaded(LANG_TAGS.GERMAN)){
        await MLKitTranslator.downloadModel(LANG_TAGS.GERMAN);
      }
  
      if(await MLKitTranslator.isModelDownloaded(LANG_TAGS.ENGLISH)){
        await MLKitTranslator.downloadModel(LANG_TAGS.ENGLISH);
      }
```

**Comment by noumantahir** [comment]
same issue, even simplest of code threw this error...

![Screenshot 2023-08-30 at 5 34 12 PM](https://github.com/yaaliuzhipeng/react-native-mlkit-translate-text/assets/6298342/718cce09-2507-40ee-a922-fec6d6444488)

```
   if(!await MLKitTranslator.isModelDownloaded(LANG_TAGS.GERMAN)){
        await MLKitTranslator.downloadModel(LANG_TAGS.GERMAN);
      }
  
      if(!await MLKitTranslator.isModelDownloaded(LANG_TAGS.ENGLISH)){
        await MLKitTranslator.downloadModel(LANG_TAGS.ENGLISH);
      }

      const _translation = await MLKitTranslator.translateText(text, LANG_TAGS.ENGLISH, LANG_TAGS.GERMAN)
```

**Comment by fukemy** [comment]
any solution now?

**Comment by JasonCareter** [comment]
Hey guys, I’m going to check out this issue and update this library to support new arch. Perhaps 1-2 week I guess

**Comment by JasonCareter** [comment]
new updates is released, check it out  , https://github.com/yaaliuzhipeng/fast-mlkit-translate-text
