### ISSUE TITLE
Missing file to import from?

### ISSUE THREAD

**Issue by xcanchal** [yaaliuzhipeng/react-native-mlkit-translate-text#5]
Hi, I just installed the package but looking at the dist files I can't find the `./MLKitEntityExtraction` file. Am I missing something? Here you can see a screenshot of the package's index.js file:

<img width="948" alt="Screenshot 2023-07-26 at 18 05 52" src="https://github.com/yaaliuzhipeng/react-native-mlkit-translate-text/assets/13048567/989aa1bb-f526-4d4f-a957-516e34161bcd">

Thanks in advance

**Comment by JasonCareter** [comment]
see [issue](https://github.com/yaaliuzhipeng/react-native-mlkit-translate-text/issues/1)
